[package]
name = "ffsend-api"
version = "0.3.2"
authors = ["Tim Visee <timvisee@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/timvisee/ffsend-api"
repository = "https://github.com/timvisee/ffsend-api"
documentation = "https://docs.rs/ffsend-api"
description = "A fully featured Firefox Send API client."
keywords = ["send", "firefox", "api"]
categories = [
    "api-bindings",
    "authentication",
    "cryptography",
    "network-programming",
]
edition = "2018"

[badges]
gitlab = { repository = "timvisee/ffsend-api", branch = "master" }

[lib]
name = "ffsend_api"
path = "src/lib.rs"

[features]
default = ["send2", "send3"]

# Support for Firefox Send v2
send2 = []

# Support for Firefox Send v3
send3 = ["websocket"]

[dependencies]
arrayref = "0.3"
base64 = "0.10"
byteorder = "1.3"
bytes = "0.4"
chrono = { version = "0.4", features = ["serde"] }
derive_builder = "0.7"
failure = "0.1"
failure_derive = "0.1"
hkdf = "0.7"
hyper = "0.12.22" # same as reqwest
mime = "0.3.7" # same as reqwest
mime_guess = "2.0.0-alpha.4"
openssl = "0.10"
regex = "1.1"
reqwest = "0.9.12"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.8"
time = "0.1"
url = "1.7"
url_serde = "0.2"
version-compare = "0.0.8"
websocket = { version = "0.22.3", optional = true }
